import type { LessonConfig } from '../../types/lesson.ts';

export const lesson4_1: LessonConfig = {
  id: 'u4-l1',
  unitId: 'unit-4',
  title: 'How Humans Perceive Color',
  description:
    'Discover that color is a human interpretation: the eye and brain construct the experience of color from light signals.',
  learningGoal:
    'Explain in plain terms that color perception is constructed by the visual system and varies across individuals.',
  estimatedMinutes: 13,
  prerequisites: ['u3-l6'],
  conceptsIntroduced: [
    'color perception',
    'retina',
    'cone',
    'rod',
    'optic nerve',
    'visual system',
    'color vision',
  ],
  interactionType: 'eye-diagram',
  glossaryTerms: [
    'color perception',
    'color vision',
    'cone',
    'rod',
    'retina',
    'optic nerve',
    'visual system',
  ],
  reviewTags: ['perception', 'vision', 'biology-basics'],
  steps: [
    {
      id: 's1',
      text: 'A digital screen emits light. But when you see a color, you are not seeing the screen itself — you are seeing the result of your eye and brain interpreting that light. Color is a perceptual experience, not a physical property of the display.',
      highlights: ['color perception', 'visual system'],
    },
    {
      id: 's2',
      text: 'Light enters the eye and lands on the retina at the back of the eye. The retina contains two types of photoreceptor cells: rods and cones. Rods respond to low-light conditions and do not contribute much to color vision. Cones are responsible for color.',
      highlights: ['retina', 'rod', 'cone'],
    },
    {
      id: 's3',
      text: 'Humans typically have three cone types, each most sensitive to a different range of wavelengths — broadly corresponding to long (red), medium (green), and short (blue). The brain compares the signals from these three cone types to construct the experience of color.',
      highlights: ['cone', 'color vision'],
    },
    {
      id: 's4',
      text: 'The retina sends signals along the optic nerve to the visual cortex in the brain, where the final experience of color is assembled. Context, memory, and surrounding colors all influence the result. Simultaneous contrast — where a color looks different depending on its neighbors — is one example.',
      highlights: ['optic nerve', 'visual system'],
    },
    {
      id: 's5',
      text: 'Because color perception depends on each individual\'s visual system, two people looking at the same interface may not perceive it identically. Good design accounts for this variation rather than assuming all viewers share the same experience.',
      highlights: ['color perception'],
    },
  ],
  challenges: [
    {
      id: 'c1',
      prompt:
        'Click through each part of the visual pathway to reveal how it contributes to color perception.',
      type: 'explore-all',
      hints: [
        'Start with the light source and follow the path into the eye.',
        'Each step has a short design implication — read it before moving on.',
      ],
      successCriteria: 'All pathway steps explored.',
    },
  ],
  quizItems: [
    {
      id: 'q1',
      prompt: 'Which cells in the retina are most relevant to color perception?',
      choices: [
        {
          id: 'a',
          label: 'Rods',
          isCorrect: false,
          explanation:
            'Rods are sensitive to low-light conditions but are not primarily responsible for color vision.',
        },
        {
          id: 'b',
          label: 'Cones',
          isCorrect: true,
          explanation:
            'Cones are the photoreceptor cells responsible for color vision. Humans typically have three types, each sensitive to a different range of wavelengths.',
        },
        {
          id: 'c',
          label: 'The optic nerve',
          isCorrect: false,
          explanation:
            'The optic nerve carries signals from the retina to the brain, but it does not process color itself.',
        },
        {
          id: 'd',
          label: 'The cornea',
          isCorrect: false,
          explanation:
            'The cornea focuses light onto the retina but does not play a role in color processing.',
        },
      ],
    },
    {
      id: 'q2',
      prompt: 'What does the optic nerve do?',
      choices: [
        {
          id: 'a',
          label: 'It converts light into electrical signals',
          isCorrect: false,
          explanation:
            'That conversion happens in the photoreceptor cells — rods and cones — in the retina.',
        },
        {
          id: 'b',
          label: 'It carries visual signals from the retina to the brain',
          isCorrect: true,
          explanation:
            'The optic nerve transmits electrical signals generated by the retina to the visual cortex in the brain, where they are processed into the experience of vision.',
        },
        {
          id: 'c',
          label: 'It adjusts the amount of light entering the eye',
          isCorrect: false,
          explanation:
            'That is the role of the iris and pupil, not the optic nerve.',
        },
        {
          id: 'd',
          label: 'It filters out ultraviolet light',
          isCorrect: false,
          explanation:
            'The lens of the eye filters UV light. The optic nerve carries signals from retina to brain.',
        },
      ],
    },
    {
      id: 'q3',
      prompt:
        'Why might the same interface color appear different to different viewers?',
      choices: [
        {
          id: 'a',
          label: 'Because screen calibration always differs between devices',
          isCorrect: false,
          explanation:
            'Display differences can contribute, but the more fundamental reason is that each person\'s visual system constructs color perception differently.',
        },
        {
          id: 'b',
          label:
            'Because color perception is constructed by each person\'s visual system, which varies',
          isCorrect: true,
          explanation:
            'Each viewer\'s visual system — including cone sensitivity, optical lens characteristics, and neural processing — produces a slightly different perceptual experience from the same physical input.',
        },
        {
          id: 'c',
          label: 'Because CSS renders colors differently in each browser',
          isCorrect: false,
          explanation:
            'Modern browsers render standard colors consistently. The variation is perceptual, not technical.',
        },
        {
          id: 'd',
          label: 'Because colors change over time due to phosphor decay',
          isCorrect: false,
          explanation:
            'That applies to older CRT displays. The main reason for perceptual differences is variation in the human visual system.',
        },
      ],
    },
  ],
  keyPoints: [
    'A screen emits light, but color is constructed by the eye and brain — it is a perceptual experience, not a physical screen property.',
    'The retina contains cones (responsible for color, concentrated at the center) and rods (sensitive to low light, at the edges).',
    'Three cone types — sensitive to different wavelength ranges — allow the brain to distinguish colors by comparing their relative signals.',
    'The optic nerve carries retinal signals to the brain, where context, memory, and surrounding colors all shape the final perception.',
    'Because each person\'s visual system is slightly different, two viewers may not perceive the same interface color identically — good design accounts for this variation.',
  ],
};
