import type { LessonConfig } from '../../types/lesson.ts';

export const lesson5_3: LessonConfig = {
  id: 'u5-l3', unitId: 'unit-5',
  title: 'Color-Only Problems and Redundant Cues',
  description: 'Learn the WCAG 1.4.1 "Use of Color" guideline, identify color-only failures in common UI patterns, and fix them by adding icons, labels, patterns, and structural cues.',
  learningGoal: 'Identify color-only communication problems and strengthen interfaces with redundant cues so meaning does not depend on hue alone.',
  estimatedMinutes: 16,
  prerequisites: ['u5-l2'],
  conceptsIntroduced: [
    'use of color',
    'redundant cue',
    'annotation',
    'chart series',
    'direct label',
    'error state',
    'info state',
    'pattern fill',
    'success state',
    'validation feedback',
    'warning state',
    'status message',
    'validation state',
  ],
  interactionType: 'state-workshop',
  glossaryTerms: [
    'use of color',
    'redundant cue',
    'annotation',
    'chart series',
    'direct label',
    'error state',
    'info state',
    'pattern fill',
    'success state',
    'validation feedback',
    'warning state',
    'status message',
    'validation state',
  ],
  reviewTags: ['color-only', 'wcag', 'redundancy', 'states', 'charts', 'backup-cues'],
  steps: [
    {
      id: 's1',
      text: 'In Unit 4 you observed that designs relying on hue alone break when color perception varies. WCAG 1.4.1 "Use of Color" formalizes this observation: color must not be the only visual means of conveying information. The goal is not to remove color but to ensure it is not the sole carrier of meaning.',
      highlights: ['use of color'],
    },
    {
      id: 's2',
      text: 'Semantic states — success, warning, error, info — are a fundamental UI pattern. Most start with color alone: a green badge, a yellow badge, a red badge. Each state should communicate through at least two channels: a success state can use green color + a checkmark icon + the label "Success."',
      highlights: ['success state', 'warning state', 'error state', 'info state'],
    },
    {
      id: 's3',
      text: 'Form validation is a specific case. A red border alone is weak. The strongest form error combines: a colored border or outline, an error icon, and a clear text message beneath the field. Validation feedback should answer "what went wrong and how to fix it."',
      highlights: ['validation feedback', 'status message'],
    },
    {
      id: 's4',
      text: 'Charts with multiple series are especially vulnerable. Two strong fixes: direct labels placed adjacent to each line or bar (eliminating the need for a color-only legend) and pattern fills — hatching or textures — that make series distinguishable without relying on hue.',
      highlights: ['direct label', 'pattern fill', 'chart series', 'annotation'],
    },
    {
      id: 's5',
      text: 'The principle is redundancy: meaning carried by two or more signals. If color fades under CVD simulation, the icon or label still communicates. A good test: if you removed all color and every element\'s meaning was still clear, the design is robust.',
      highlights: ['redundant cue'],
    },
  ],
  challenges: [
    {
      id: 'c1',
      prompt: 'Add at least one non-color cue to each of the four semantic states. Toggle icon, label, and border style to build a more robust state system.',
      type: 'add-cues',
      hints: [
        'Toggle at least one of the three cues (icon, label, border) for each state card.',
        'All four states need at least one cue enabled before the challenge is complete.',
        'Start by asking: if I removed hue, what would still communicate meaning?',
      ],
      successCriteria: 'All four states have at least one non-color cue enabled.',
    },
  ],
  quizItems: [
    {
      id: 'q1',
      prompt: 'What does WCAG 1.4.1 "Use of Color" require?',
      choices: [
        {
          id: 'a',
          label: 'That interfaces use no more than five colors',
          isCorrect: false,
          explanation: 'WCAG does not limit the number of colors — it requires that color is not the sole means of conveying information.',
        },
        {
          id: 'b',
          label: 'That color is not the only visual means of conveying information',
          isCorrect: true,
          explanation: 'If removing the color difference removes all meaning, the design has a color-alone problem. A second channel (icon, label, pattern) must also carry the meaning.',
        },
        {
          id: 'c',
          label: 'That all colors must pass contrast ratio thresholds',
          isCorrect: false,
          explanation: 'Contrast ratios are covered by separate WCAG criteria. 1.4.1 is specifically about whether color is the sole information carrier.',
        },
        {
          id: 'd',
          label: 'That color must be removed from interactive elements',
          isCorrect: false,
          explanation: 'Color is encouraged — it just cannot be the only signal. The goal is redundancy, not removal.',
        },
      ],
    },
    {
      id: 'q2',
      prompt: 'Why is a green border alone a weak success message?',
      choices: [
        {
          id: 'a',
          label: 'Because green is not a good success color',
          isCorrect: false,
          explanation: 'Green is conventionally associated with success. The weakness is not the color choice — it is relying on color alone.',
        },
        {
          id: 'b',
          label: 'Because it conveys meaning only through hue, which may not be distinguishable under CVD or low-color conditions',
          isCorrect: true,
          explanation: 'A green border is invisible as a "success" signal to someone who cannot perceive that hue. Adding an icon and text makes the success state robust.',
        },
        {
          id: 'c',
          label: 'Because borders should not be used in accessible designs',
          isCorrect: false,
          explanation: 'Borders are a perfectly valid UI element. The issue is using color as the only channel.',
        },
        {
          id: 'd',
          label: 'Because success messages must always use a modal dialog',
          isCorrect: false,
          explanation: 'Inline success feedback is a common and appropriate pattern. The form of feedback is not the issue — the lack of backup cues is.',
        },
      ],
    },
    {
      id: 'q3',
      prompt: 'What does redundancy mean in accessible design?',
      choices: [
        {
          id: 'a',
          label: 'Repeating the same content multiple times unnecessarily',
          isCorrect: false,
          explanation: 'Redundancy here means providing meaning through more than one visual channel.',
        },
        {
          id: 'b',
          label: 'Conveying meaning through more than one visual channel so that losing any one does not break the design',
          isCorrect: true,
          explanation: 'Redundant cues make designs robust — if color is lost, icons and labels still communicate.',
        },
        {
          id: 'c',
          label: 'Using the same color for all states to reduce confusion',
          isCorrect: false,
          explanation: 'Same color for all states would remove distinction entirely.',
        },
        {
          id: 'd',
          label: 'Adding extra whitespace to improve readability',
          isCorrect: false,
          explanation: 'Whitespace is a layout concept, not a redundancy strategy.',
        },
      ],
    },
  ],
  keyPoints: [
    'WCAG 1.4.1 requires that color is not the only means of conveying information — color should support meaning, not carry it alone.',
    'Semantic states (success, warning, error, info) should use at least two channels: color plus icon, label, or border style.',
    'The strongest form validation combines a colored border, an error icon, and a descriptive text message.',
    'Direct labels on chart series eliminate the need for color-coded legends. Pattern fills make bars or areas distinguishable without hue.',
    'Redundancy means carrying meaning through two or more signals — a robust design remains clear even if color is removed.',
  ],
};
